services:
  api:
    container_name: fastapi-app
    build: .
    entrypoint: [ "sh", "./entrypoint.sh" ]
    depends_on:
      [postgres]
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app # removed ':ro' for write access
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
  postgres:
    container_name: fastapi-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: