"""add missing columns to users

Revision ID: fcd7d9773e30
Revises: c74a77ad8ccc
Create Date: 2025-04-15 21:00:13.942648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fcd7d9773e30"
down_revision: Union[str, None] = "c74a77ad8ccc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published", sa.Boolean(), nullable=False))
    op.add_column("posts", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("posts", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("posts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_posts_content"), "posts", ["content"], unique=False)
    op.create_index(op.f("ix_posts_title"), "posts", ["title"], unique=False)
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"])
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=False))
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_index(op.f("ix_posts_title"), table_name="posts")
    op.drop_index(op.f("ix_posts_content"), table_name="posts")
    op.drop_column("posts", "user_id")
    op.drop_column("posts", "updated_at")
    op.drop_column("posts", "created_at")
    op.drop_column("posts", "published")
    # ### end Alembic commands ###
